DKPInfo = {
["date"] = "18.08.20 17:23:41",
["timestamp"] = "1597771421",
["total_players"] = 123,
["total_items"] = 26,
}
gdkp = {
["players"] = {
["apace"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Druide",
},
["Argok"] = {
["DKP"] = -68,
["dkp_earned"] = 36,
["dkp_spend"] = 120,
["dkp_adjust"] = 18.1,
["dkp_current"] = -68.91,
["class"] = "Krieger",
},
["Aryuna"] = {
["DKP"] = 63,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 30.31,
["dkp_current"] = 62.08,
["class"] = "Schamane",
},
["Atomar"] = {
["DKP"] = 33,
["dkp_earned"] = 24,
["dkp_spend"] = 0,
["dkp_adjust"] = 10.83,
["dkp_current"] = 32.55,
["class"] = "Hexenmeister",
},
["Avûs"] = {
["DKP"] = 20,
["dkp_earned"] = 22,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.99,
["dkp_current"] = 19.01,
["class"] = "Jäger",
},
["Barbozza"] = {
["DKP"] = 40,
["dkp_earned"] = 6,
["dkp_spend"] = 0,
["dkp_adjust"] = 37.36,
["dkp_current"] = 39.42,
["class"] = "Priester",
},
["Bibikoksberg"] = {
["DKP"] = 3,
["dkp_earned"] = 2,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.5,
["dkp_current"] = 2.45,
["class"] = "Krieger",
},
["Blackagony"] = {
["DKP"] = 41,
["dkp_earned"] = 6,
["dkp_spend"] = 0,
["dkp_adjust"] = 38.27,
["dkp_current"] = 40.24,
["class"] = "Hexenmeister",
},
["Breituxs"] = {
["DKP"] = 48,
["dkp_earned"] = 36,
["dkp_spend"] = 10,
["dkp_adjust"] = 25.52,
["dkp_current"] = 47.77,
["class"] = "Schurke",
},
["Bärspektive"] = {
["DKP"] = -2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.69,
["dkp_current"] = -2.69,
["class"] = "Druide",
},
["Doktorwho"] = {
["DKP"] = 79,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 48.93,
["dkp_current"] = 78.84,
["class"] = "Priester",
},
["Dreadhead"] = {
["DKP"] = 25,
["dkp_earned"] = 36,
["dkp_spend"] = 20,
["dkp_adjust"] = 9.5,
["dkp_current"] = 24.35,
["class"] = "Schurke",
},
["DrGurke"] = {
["DKP"] = 6,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 5.67,
["dkp_current"] = 5.1,
["class"] = "Hexenmeister",
},
["Elgrecco"] = {
["DKP"] = 65,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 32.76,
["dkp_current"] = 64.28,
["class"] = "Hexenmeister",
},
["Flottiløl"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.7,
["dkp_current"] = 0.63,
["class"] = "Priester",
},
["gagam"] = {
["DKP"] = 24,
["dkp_earned"] = 24,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 24,
["class"] = "Magier",
},
["Gilo"] = {
["DKP"] = 72,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 41.01,
["dkp_current"] = 71.71,
["class"] = "Hexenmeister",
},
["Gk"] = {
["DKP"] = 7,
["dkp_earned"] = 2,
["dkp_spend"] = 0,
["dkp_adjust"] = 4.79,
["dkp_current"] = 6.31,
["class"] = "Krieger",
},
["Gromsuk"] = {
["DKP"] = 66,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 33.7,
["dkp_current"] = 65.13,
["class"] = "Schamane",
},
["Hacker"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Schurke",
},
["Hackerman"] = {
["DKP"] = 3,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 2.33,
["dkp_current"] = 2.1,
["class"] = "Krieger",
},
["Hasenpfote"] = {
["DKP"] = -9,
["dkp_earned"] = 14,
["dkp_spend"] = 60,
["dkp_adjust"] = 36.71,
["dkp_current"] = -9.29,
["class"] = "Druide",
},
["Himbster"] = {
["DKP"] = 65,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 32.49,
["dkp_current"] = 64.04,
["class"] = "Schamane",
},
["Inferus"] = {
["DKP"] = 11,
["dkp_earned"] = 2,
["dkp_spend"] = 0,
["dkp_adjust"] = 9.4,
["dkp_current"] = 10.26,
["class"] = "Priester",
},
["Inmedias"] = {
["DKP"] = 2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 1.99,
["dkp_current"] = 1.79,
["class"] = "Krieger",
},
["Kaltherz"] = {
["DKP"] = 0,
["dkp_earned"] = 36,
["dkp_spend"] = 50,
["dkp_adjust"] = 13.81,
["dkp_current"] = -0.19,
["class"] = "Krieger",
},
["Kayujin"] = {
["DKP"] = 35,
["dkp_earned"] = 16,
["dkp_spend"] = 0,
["dkp_adjust"] = 22,
["dkp_current"] = 34.6,
["class"] = "Jäger",
},
["Landogar"] = {
["DKP"] = 50,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 15.97,
["dkp_current"] = 49.17,
["class"] = "Krieger",
},
["Legshot"] = {
["DKP"] = 78,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 47.36,
["dkp_current"] = 77.42,
["class"] = "Jäger",
},
["Lustknabe"] = {
["DKP"] = 63,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 31.24,
["dkp_current"] = 62.92,
["class"] = "Magier",
},
["Lyren"] = {
["DKP"] = 7,
["dkp_earned"] = 14,
["dkp_spend"] = 0,
["dkp_adjust"] = -7.17,
["dkp_current"] = 6.35,
["class"] = "Magier",
},
["Malgan"] = {
["DKP"] = 50,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 16.42,
["dkp_current"] = 49.58,
["class"] = "Krieger",
},
["Midget"] = {
["DKP"] = 36,
["dkp_earned"] = 16,
["dkp_spend"] = 0,
["dkp_adjust"] = 23.16,
["dkp_current"] = 35.64,
["class"] = "Krieger",
},
["Moard"] = {
["DKP"] = 45,
["dkp_earned"] = 6,
["dkp_spend"] = 0,
["dkp_adjust"] = 42.49,
["dkp_current"] = 44.04,
["class"] = "Schamane",
},
["MonkeyDArlee"] = {
["DKP"] = 4,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 3.66,
["dkp_current"] = 3.29,
["class"] = "Krieger",
},
["Muffelfutt"] = {
["DKP"] = 56,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 23.3,
["dkp_current"] = 55.77,
["class"] = "Magier",
},
["Møtz"] = {
["DKP"] = 38,
["dkp_earned"] = 36,
["dkp_spend"] = 40,
["dkp_adjust"] = 42.95,
["dkp_current"] = 37.46,
["class"] = "Magier",
},
["Narziß"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Schurke",
},
["Nesrar"] = {
["DKP"] = 77,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 46.75,
["dkp_current"] = 76.88,
["class"] = "Schamane",
},
["Okat"] = {
["DKP"] = 70,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 39.09,
["dkp_current"] = 69.98,
["class"] = "Druide",
},
["Palim"] = {
["DKP"] = 12,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 12.39,
["dkp_current"] = 11.15,
["class"] = "Magier",
},
["Phi"] = {
["DKP"] = 14,
["dkp_earned"] = 22,
["dkp_spend"] = 0,
["dkp_adjust"] = -8.26,
["dkp_current"] = 13.74,
["class"] = "Schurke",
},
["Pâd"] = {
["DKP"] = 38,
["dkp_earned"] = 14,
["dkp_spend"] = 0,
["dkp_adjust"] = 27.33,
["dkp_current"] = 37.4,
["class"] = "Priester",
},
["Quyncy"] = {
["DKP"] = -26,
["dkp_earned"] = 36,
["dkp_spend"] = 60,
["dkp_adjust"] = -1.6,
["dkp_current"] = -26.64,
["class"] = "Priester",
},
["Rassputin"] = {
["DKP"] = -72,
["dkp_earned"] = 36,
["dkp_spend"] = 150,
["dkp_adjust"] = 41.91,
["dkp_current"] = -72.09,
["class"] = "Hexenmeister",
},
["Raynzx"] = {
["DKP"] = 70,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 38.58,
["dkp_current"] = 69.52,
["class"] = "Magier",
},
["Repa"] = {
["DKP"] = 18,
["dkp_earned"] = 36,
["dkp_spend"] = 50,
["dkp_adjust"] = 36.48,
["dkp_current"] = 17.63,
["class"] = "Magier",
},
["Rondalis"] = {
["DKP"] = 47,
["dkp_earned"] = 34,
["dkp_spend"] = 0,
["dkp_adjust"] = 16.43,
["dkp_current"] = 46.19,
["class"] = "Priester",
},
["Saidar"] = {
["DKP"] = 75,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 43.91,
["dkp_current"] = 74.32,
["class"] = "Priester",
},
["Savalox"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Hexenmeister",
},
["Schamaninger"] = {
["DKP"] = -23,
["dkp_earned"] = 36,
["dkp_spend"] = 100,
["dkp_adjust"] = 40.81,
["dkp_current"] = -23.47,
["class"] = "Schamane",
},
["Shadowbírd"] = {
["DKP"] = 27,
["dkp_earned"] = 36,
["dkp_spend"] = 50,
["dkp_adjust"] = 40.5,
["dkp_current"] = 26.25,
["class"] = "Jäger",
},
["Shatoyama"] = {
["DKP"] = 67,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 35.32,
["dkp_current"] = 66.59,
["class"] = "Krieger",
},
["Taxol"] = {
["DKP"] = 14,
["dkp_earned"] = 4,
["dkp_spend"] = 0,
["dkp_adjust"] = 11.12,
["dkp_current"] = 13.81,
["class"] = "Schurke",
},
["Telli"] = {
["DKP"] = 9,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 9.89,
["dkp_current"] = 8.9,
["class"] = "Schurke",
},
["Themask"] = {
["DKP"] = 48,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 14.6,
["dkp_current"] = 47.94,
["class"] = "Jäger",
},
["Thurikan"] = {
["DKP"] = 52,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 18.62,
["dkp_current"] = 51.56,
["class"] = "Krieger",
},
["Tosuau"] = {
["DKP"] = -69,
["dkp_earned"] = 36,
["dkp_spend"] = 130,
["dkp_adjust"] = 27.76,
["dkp_current"] = -69.22,
["class"] = "Krieger",
},
["Trollimba"] = {
["DKP"] = 50,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 16.36,
["dkp_current"] = 49.52,
["class"] = "Priester",
},
["Trqzthree"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Magier",
},
["Täuschung"] = {
["DKP"] = 33,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.8,
["dkp_current"] = 32.28,
["class"] = "Schurke",
},
["Watschenbaum"] = {
["DKP"] = 18,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 19.77,
["dkp_current"] = 17.79,
["class"] = "Krieger",
},
["Wolbeck"] = {
["DKP"] = 23,
["dkp_earned"] = 36,
["dkp_spend"] = 20,
["dkp_adjust"] = 8.38,
["dkp_current"] = 22.34,
["class"] = "Schamane",
},
["Xatakus"] = {
["DKP"] = 71,
["dkp_earned"] = 36,
["dkp_spend"] = 0,
["dkp_adjust"] = 39.23,
["dkp_current"] = 70.11,
["class"] = "Magier",
},
["Xraa"] = {
["DKP"] = -10,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -10.62,
["dkp_current"] = -10.62,
["class"] = "Schamane",
},
["Yologott"] = {
["DKP"] = 9,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 8.94,
["dkp_current"] = 8.05,
["class"] = "Krieger",
},
["Zamie"] = {
["DKP"] = 1,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.78,
["dkp_current"] = 0.7,
["class"] = "Schurke",
},
["Zeluu"] = {
["DKP"] = -14,
["dkp_earned"] = 32,
["dkp_spend"] = 0,
["dkp_adjust"] = -46.1,
["dkp_current"] = -14.1,
["class"] = "Schurke",
},
["Zypnek"] = {
["DKP"] = 52,
["dkp_earned"] = 24,
["dkp_spend"] = 0,
["dkp_adjust"] = 30.54,
["dkp_current"] = 51.49,
["class"] = "Magier",
},
}
}
