DKPInfo = {
["date"] = "11.08.20 07:28:33",
["timestamp"] = "1597130913",
["total_players"] = 121,
["total_items"] = 0,
}
gdkp = {
["players"] = {
["Argok"] = {
["DKP"] = 19,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 18.1,
["dkp_current"] = 18.1,
["class"] = "Krieger",
},
["Aryuna"] = {
["DKP"] = 31,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 30.31,
["dkp_current"] = 30.31,
["class"] = "Schamane",
},
["Atomar"] = {
["DKP"] = 21,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 20.83,
["dkp_current"] = 20.83,
["class"] = "Hexenmeister",
},
["Avûs"] = {
["DKP"] = -2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.99,
["dkp_current"] = -2.99,
["class"] = "Jäger",
},
["Barbozza"] = {
["DKP"] = 38,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 37.36,
["dkp_current"] = 37.36,
["class"] = "Priester",
},
["Bibikoksberg"] = {
["DKP"] = 1,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.5,
["dkp_current"] = 0.5,
["class"] = "Krieger",
},
["Blackagony"] = {
["DKP"] = 39,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 38.27,
["dkp_current"] = 38.27,
["class"] = "Hexenmeister",
},
["Breituxs"] = {
["DKP"] = 26,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 25.52,
["dkp_current"] = 25.52,
["class"] = "Schurke",
},
["Bärspektive"] = {
["DKP"] = -2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.69,
["dkp_current"] = -2.69,
["class"] = "Druide",
},
["Doktorwho"] = {
["DKP"] = 49,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 48.93,
["dkp_current"] = 48.93,
["class"] = "Priester",
},
["Dreadhead"] = {
["DKP"] = 10,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 9.5,
["dkp_current"] = 9.5,
["class"] = "Schurke",
},
["DrGurke"] = {
["DKP"] = 6,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 5.67,
["dkp_current"] = 5.67,
["class"] = "Hexenmeister",
},
["Elgrecco"] = {
["DKP"] = 33,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 32.76,
["dkp_current"] = 32.76,
["class"] = "Hexenmeister",
},
["Flottiløl"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.7,
["dkp_current"] = 0,
["class"] = "Priester",
},
["Gilo"] = {
["DKP"] = 42,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 41.01,
["dkp_current"] = 41.01,
["class"] = "Hexenmeister",
},
["Gk"] = {
["DKP"] = 5,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 4.79,
["dkp_current"] = 4.79,
["class"] = "Krieger",
},
["Gromsuk"] = {
["DKP"] = 34,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 33.7,
["dkp_current"] = 33.7,
["class"] = "Schamane",
},
["Hacker"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Schurke",
},
["Hackerman"] = {
["DKP"] = 3,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 2.33,
["dkp_current"] = 2.33,
["class"] = "Krieger",
},
["Hasenpfote"] = {
["DKP"] = 37,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 36.71,
["dkp_current"] = 36.71,
["class"] = "Druide",
},
["Himbster"] = {
["DKP"] = 33,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 32.49,
["dkp_current"] = 32.49,
["class"] = "Schamane",
},
["Inferus"] = {
["DKP"] = 10,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 9.4,
["dkp_current"] = 9.4,
["class"] = "Priester",
},
["Inmedias"] = {
["DKP"] = 2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 1.99,
["dkp_current"] = 1.99,
["class"] = "Krieger",
},
["Kaltherz"] = {
["DKP"] = 14,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 13.81,
["dkp_current"] = 13.81,
["class"] = "Krieger",
},
["Kayujin"] = {
["DKP"] = 22,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 22,
["dkp_current"] = 22,
["class"] = "Jäger",
},
["Landogar"] = {
["DKP"] = 16,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 15.97,
["dkp_current"] = 15.97,
["class"] = "Krieger",
},
["Legshot"] = {
["DKP"] = 48,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 47.36,
["dkp_current"] = 47.36,
["class"] = "Jäger",
},
["Lustknabe"] = {
["DKP"] = 32,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 31.24,
["dkp_current"] = 31.24,
["class"] = "Magier",
},
["Lyren"] = {
["DKP"] = -7,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -7.17,
["dkp_current"] = -7.17,
["class"] = "Magier",
},
["Malgan"] = {
["DKP"] = 17,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 16.42,
["dkp_current"] = 16.42,
["class"] = "Krieger",
},
["Midget"] = {
["DKP"] = 24,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 23.16,
["dkp_current"] = 23.16,
["class"] = "Krieger",
},
["Moard"] = {
["DKP"] = 43,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 42.49,
["dkp_current"] = 42.49,
["class"] = "Schamane",
},
["MonkeyDArlee"] = {
["DKP"] = 4,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 3.66,
["dkp_current"] = 3.66,
["class"] = "Krieger",
},
["Muffelfutt"] = {
["DKP"] = 24,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 23.3,
["dkp_current"] = 23.3,
["class"] = "Magier",
},
["Møtz"] = {
["DKP"] = 43,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 42.95,
["dkp_current"] = 42.95,
["class"] = "Magier",
},
["Narziß"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Schurke",
},
["Nesrar"] = {
["DKP"] = 47,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 46.75,
["dkp_current"] = 46.75,
["class"] = "Schamane",
},
["Okat"] = {
["DKP"] = 40,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 39.09,
["dkp_current"] = 39.09,
["class"] = "Druide",
},
["Palim"] = {
["DKP"] = 13,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 12.39,
["dkp_current"] = 12.39,
["class"] = "Magier",
},
["Phi"] = {
["DKP"] = -8,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -8.26,
["dkp_current"] = -8.26,
["class"] = "Schurke",
},
["Pâd"] = {
["DKP"] = 28,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 27.33,
["dkp_current"] = 27.33,
["class"] = "Priester",
},
["Quyncy"] = {
["DKP"] = -1,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -1.6,
["dkp_current"] = -1.6,
["class"] = "Priester",
},
["Rassputin"] = {
["DKP"] = 42,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 41.91,
["dkp_current"] = 41.91,
["class"] = "Hexenmeister",
},
["Raynzx"] = {
["DKP"] = 39,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 38.58,
["dkp_current"] = 38.58,
["class"] = "Magier",
},
["Repa"] = {
["DKP"] = 37,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 36.48,
["dkp_current"] = 36.48,
["class"] = "Magier",
},
["Rondalis"] = {
["DKP"] = 31,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 30.43,
["dkp_current"] = 30.43,
["class"] = "Priester",
},
["Saidar"] = {
["DKP"] = 44,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 43.91,
["dkp_current"] = 43.91,
["class"] = "Priester",
},
["Savalox"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Hexenmeister",
},
["Schamaninger"] = {
["DKP"] = 41,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 40.81,
["dkp_current"] = 40.81,
["class"] = "Schamane",
},
["Shadowbírd"] = {
["DKP"] = 41,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 40.5,
["dkp_current"] = 40.5,
["class"] = "Jäger",
},
["Shatoyama"] = {
["DKP"] = 36,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 35.32,
["dkp_current"] = 35.32,
["class"] = "Krieger",
},
["Taxol"] = {
["DKP"] = 12,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 11.12,
["dkp_current"] = 11.12,
["class"] = "Schurke",
},
["Telli"] = {
["DKP"] = 10,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 9.89,
["dkp_current"] = 9.89,
["class"] = "Schurke",
},
["Themask"] = {
["DKP"] = 15,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 14.6,
["dkp_current"] = 14.6,
["class"] = "Jäger",
},
["Thurikan"] = {
["DKP"] = 19,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 18.62,
["dkp_current"] = 18.62,
["class"] = "Krieger",
},
["Tosuau"] = {
["DKP"] = 28,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 27.76,
["dkp_current"] = 27.76,
["class"] = "Krieger",
},
["Trollimba"] = {
["DKP"] = 17,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 16.36,
["dkp_current"] = 16.36,
["class"] = "Priester",
},
["Trqzthree"] = {
["DKP"] = 0,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0,
["dkp_current"] = 0,
["class"] = "Magier",
},
["Täuschung"] = {
["DKP"] = -2,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -2.8,
["dkp_current"] = -2.8,
["class"] = "Schurke",
},
["Watschenbaum"] = {
["DKP"] = 20,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 19.77,
["dkp_current"] = 19.77,
["class"] = "Krieger",
},
["Wolbeck"] = {
["DKP"] = 9,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 8.38,
["dkp_current"] = 8.38,
["class"] = "Schamane",
},
["Xatakus"] = {
["DKP"] = 40,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 39.23,
["dkp_current"] = 39.23,
["class"] = "Magier",
},
["Xraa"] = {
["DKP"] = -10,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -10.62,
["dkp_current"] = -10.62,
["class"] = "Schamane",
},
["Yologott"] = {
["DKP"] = 9,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 8.94,
["dkp_current"] = 8.94,
["class"] = "Krieger",
},
["Zamie"] = {
["DKP"] = 1,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 0.78,
["dkp_current"] = 0.78,
["class"] = "Schurke",
},
["Zeluu"] = {
["DKP"] = -28,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = -28.1,
["dkp_current"] = -28.1,
["class"] = "Schurke",
},
["Zypnek"] = {
["DKP"] = 31,
["dkp_earned"] = 0,
["dkp_spend"] = 0,
["dkp_adjust"] = 30.54,
["dkp_current"] = 30.54,
["class"] = "Magier",
},
}
}
